### ISSUE TITLE
proxy redirect 

### ISSUE THREAD

**Issue by yarochewsky** [xdp-project/xdp-tutorial#119]
Is redirecting to a local proxy simply a matter of rewriting the destination ports on ingress?

I'm able to rewrite the ports, but no traffic passing through the proxy.

```
    if (dst == 80)  {
         tcp_hdr->dest = bpf_htons(8080);
   }
```

```  <idle>-0     [003] ..s. 12977.347141: 0: ingress: dst is 80, new dest is: 8080```

**Comment by tohojo** [comment]
Daniel Fonseca Yarochewsky <notifications@github.com> writes:

> Is redirecting to a local proxy simply a matter of rewriting the destination ports on ingress?
>
> I'm able to rewrite the ports, but no traffic passing through the proxy.
>
> ```          <idle>-0     [003] ..s. 12977.347141: 0: ingress: dst is 80, new dest is: 8080```

I'm assuming this is TCP, right? My guess would be that your problem is
that the proxy replies back from that same port (8080), which will
confuse the client (i.e., it can't match the TCP packets to its socket).
This is why things like DNAT in iptables will use conntrack to also
rewrite the replies so the sender is none-the-wiser. So you'd need to do
something similar for your use case, for example by rewriting the reply
in the TC hook...

**Comment by yarochewsky** [comment]
That makes sense, @tohojo. Thanks a lot! Always saving me

**Comment by tohojo** [comment]
You're welcome! :)
