### ISSUE TITLE
How to bind two AF_XDP sockets to different queues on different devices while sharing the same umem?

### ISSUE THREAD

**Issue by zengziteng** [xdp-project/xdp-tutorial#231]
### Problem Description:
I have a manager process and a client process. Both of them have an AF_XDP socket and I want to share the umem between them. The umem and fill/completion ring are created by the manager process and the client process will reuse them. The socket in the manager process (socket 1) is bind normally with sxdp_flags = 0 and sxdp_shared_umem_fd = 0. Then I get the file descriptor of socket 1 in the client process using pidfd_getfd. The socket in the client process (socket 2) is bind with sxdp_flags = XDP_SHARED_UMEM and sxdp_shared_umem_fd = shared_fd (file descriptor of socket 1).

When I bind socket 2 to the same device and queue id as socket 1, this works fine. But when I try to bind socket 2 to different device or different queue id, the bind function fails and the errno is 22 (invalid argument). Maybe this has nothing to do with multiple processes environment. I have tried this in a single process and the result is the same. How can I share umem between queue ids and between network devices? Do you have any sample code?

### System:
- Ubuntu 20.04.2 LTS
- kernel 5.10.48

### NIC:
- Intel® 10GbE PCI Express adapters
- driver: ixgbe
- version: 5.10.48
- rx queue: 64

**Comment by tohojo** [comment]
No idea if that's possible. I guess @magnus-karlsson would know :)

**Comment by magnus-karlsson** [comment]
This is supported. You can find sample code in the Linux source tree samples/bpf/xsk_fwd.c. The difference between sharing the same netdev and queue id with the case when you share a different netdev and/or queue id is that you have to create another set of completion and fill rings in the latter case. If you have not created your own pair for each socket, the bind will fail. This is in contrast to the former case, in which the fill ring and completion ring are shared between the sockets since they are all bound to the same netdev and queue id.

**Comment by zengziteng** [comment]
Thank you for your valuable information!
