### ISSUE TITLE
ixgbe driver doesn't work on TX without attaching eBPF

### ISSUE THREAD

**Issue by cyanide-burnout** [xdp-project/xdp-tutorial#273]
He have found that ixgbe driver doesn't work on TX without attaching eBPF, when we need TX only without RX.
And it seems here is a reason of issue:
https://github.com/torvalds/linux/blob/master/drivers/net/ethernet/intel/ixgbe/ixgbe_xsk.c#L511

**Comment by magnus-karlsson** [comment]
Interesting! That is actually different from i40e and ice that does not have this check in xsk_wakeup. This check has been there since the first version of this driver. Might just be a mistake. Anyway, could you please post this to the Intel-wired-lan list (https://lists.osuosl.org/mailman/listinfo/intel-wired-lan) and close it here? On that list, your issue will be taken care of by the people in charge of the driver and anyone can weigh in if there actually is a reason for the check.

**Comment by magnus-karlsson** [comment]
All drivers have this test, though hidden behind a function in i40e and ice, so let us leave it like that.
