### ISSUE TITLE
'xsk_socket__create_shared' function throws a segmentation error

### ISSUE THREAD

**Issue by arukshani** [xdp-project/xdp-tutorial#351]
Hi,

I've been trying to extend the 'advanced03-AF_XDP' program to use the same UMEM with multiple xdp sockets that belong to different NICs. However, the following line throws a segmentation fault error when I run my program.  

Any idea why I get this error and how to get it fixed? 

```
ret = xsk_socket__create_shared(&xsk_info->xsk, cfg->ifname,
				 cfg->xsk_if_queue, umem->umem, &xsk_info->rx,
				 &xsk_info->tx, &xsk_info->fq,  &xsk_info->cq, &xsk_cfg);
```

Thanks!

**Comment by tohojo** [comment]
Maybe @magnus-karlsson can answer this?

**Comment by magnus-karlsson** [comment]
Hard to say since I do not know what the values of your parameters are. But maybe you have not created dedicated fill and completion rings for each socket? That is the difference between sharing sockets between the same netdev/queue_id and different netdevs/queue_ids. Take a look at the AF_XDP_forwarding example.

**Comment by arukshani** [comment]
thanks! AF_XDP_forwarding example works.
