### ISSUE TITLE
[basic01-xdp-pass] error libbpf: failed to load object 'xdp-dispatcher.o'

### ISSUE THREAD

**Issue by tantm3** [xdp-project/xdp-tutorial#419]
Hi everyone!

I am researching and trying to run the xdp program, but at the basic01 lab, I encounter an error when attaching the xdp program to the network interface.
I run this command and it shown a lot of error
```
./xdp_pass_user --dev lo

# Error 
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: prog 'xdp_pass': BPF program load failed: Invalid argument
libbpf: prog 'xdp_pass': failed to load: -22
libbpf: failed to load object 'xdp-dispatcher.o'
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: prog 'xdp_pass': BPF program load failed: Argument list too long
libbpf: prog 'xdp_pass': failed to load: -7
libbpf: failed to load object 'xdp-dispatcher.o'
libxdp: Compatibility check for dispatcher program failed: Argument list too long
libxdp: Falling back to loading single prog without dispatcher
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: prog 'xdp_pass': BPF program load failed: Invalid argument
libbpf: prog 'xdp_pass': failed to load: -22
libbpf: failed to load object 'xdp-dispatcher.o'
Success: Loading XDP prog name:xdp_prog_simple(id:549) on device:lo(ifindex:1)

```

The program attached to the interface even though we have a lot of error there, and I check the interface status and it's not the same with the output that expected from the lab.
My output 
```
CURRENT XDP PROGRAM STATUS:

Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     xdp_prog_simple   skb      549  3b185187f1855c4c 
ens3                   <No XDP program loaded!>
ens4                   <No XDP program loaded!>

```
Expected output

```
CURRENT XDP PROGRAM STATUS:

Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     xdp_dispatcher    skb      486  94d5f00c20184d17
 =>              50     xdp_prog_simple           493  3b185187f1855c4c  XDP_PASS
```

Here is my kernel information and version of all the tools that I used
- clang + llvm: version 17
- Ubuntu version 20.24
- Kernel: 5.4.0-156-generic

So, do I need to install xdp-dispatcher I think the dispatcher is not exist in the xdp-tools repo here: https://github.com/xdp-project/xdp-tools

Thanks for reading my question!

**Comment by tohojo** [comment]
You get the error because your kernel is too old to support the
dispatcher for multi-prog attachment. But as you can see, libxdp
automatically falls back to loading your program as the only one on the
interface. This is expected behaviour on that kernel, and you can
complete the tutorial this way; but if you want support for loading
multiple XDP programs on the same interface, you'll need to upgrade to a
newer kernel version.

**Comment by tantm3** [comment]
Hi @tohojo,
Thanks for your response!

I am still confused about the output of the `xdp-loader status`
I can't see the `XDP_PASS` from the `Chain actions` column, so is that still the expected output?
And could you please give me a hint to find the kernel version that supports xdp-dispatcher?

**Comment by tohojo** [comment]
tantm3 ***@***.***> writes:

> Hi @tohojo,
> Thanks for your response!
>
> I am still confused about the output of the `xdp-loader status`
> I can't see the `XDP_PASS` from the `Chain actions` column, so is that
> still the expected output?

Well, there are no chain actions, because there is no chain of programs
(only a single program which is the one you loaded). The "chain actions"
means "we will call the next program if the current one returns this
action", which is a logic implemented in the XDP dispatcher (and
irrelevant if there's only a single program).

> And could you please give me a hint to find the kernel version that
> supports xdp-dispatcher?

This is documented in the libxdp man page, also available here:
https://github.com/xdp-project/xdp-tools/tree/master/lib/libxdp#kernel-and-bpf-program-feature-compatibility

**Comment by tantm3** [comment]
Thanks for your clarification!
I will try a newer kernel version.
So, I will close this one here because it's not actually an issue.
